// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on

import { WebSocket } from "ws";
import { IncomingPacket, OutgoingPacket } from "./data/zonecontrollers/packets";
import { BatteryCommands, LightsCommands, Zones } from "./data/zonecontrollers/zonecontrollers";
import { ResolvedInterface } from "./helpers/ipc/hardware/network-config";

// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
}

interface WebSocketContext {
    send: (message: OutgoingPacket, zone: Zones) => void;
    onThrottleMessage: (callback: (throttleMessage: string) => void) => void;
}

interface AppContext {
    getVersion: () => Promise<string>;
    toggleAnalytics: (enabled: boolean) => Promise<boolean>;
    getAnalyticsUrl: () => Promise<string>;
    setAnalyticsUrl: (url: string) => Promise<string>;
    checkAnalyticsConnection: (url: string) => Promise<boolean>;
    setLogLevel: (level: string) => Promise<string>;
    getLogLevel: () => Promise<string>;
    getAnalyticsInterface: () => Promise<ResolvedInterface | null>;
    setAnalyticsInterface: (mac: string | null) => Promise<ResolvedInterface | null>;
}

interface SeroContext {
    // zc_lights
    sendLightsCommand: (command: LightsCommands, value?: boolean | boolean[]) => void;
    onLightsMessage: (callback: (lightsMessage: string) => void) => void;
    // zc_battery
    sendBatteryMessage: (command: BatteryCommands, value?: boolean | boolean[]) => void;
    onBatteryMessage: (callback: (batteryMessage: string) => void) => void;
}

interface HardwareContext {
    getAvailableNetworkInterfaces: () => Promise<unknown>;
    getNetworkInterface: () => Promise<ResolvedInterface | null>;
    setNetworkInterface: (mac: string) => Promise<ResolvedInterface | null>;
}


declare global {
    interface Window {
        themeMode: ThemeModeContext;
        electronWindow: ElectronWindow;
        websocket: WebSocketContext;
        sero: SeroContext;
        app: AppContext;
        hardware: HardwareContext;
    }
} 
