import { StateCreator } from "zustand"
import type { LogLevel } from "@/lib/logger"

export interface SystemSlice {
    screenBrightness: number
    adminPin: string,
    adminMode: boolean,
    appVersion: string,
    analyticsEnabled: boolean,
    analyticsBackendUrl: string,
    analyticsConnected: boolean,
    gokartLanConnected: boolean,
    showParticleEffects: boolean,
    logLevel: LogLevel,
    autoStart: boolean,
    fullscreenOnStartup: boolean,
    devToolsEnabled: boolean,
    setScreenBrightness: (screenBrightness: number) => void,
    setAdminPin: (adminPin: string) => void,
    setAppVersion: (appVersion: string) => void,
    setAnalyticsEnabled: (analyticsEnabled: boolean) => void,
    setAnalyticsBackendUrl: (url: string) => void,
    setAnalyticsConnected: (connected: boolean) => void,
    setGokartLanConnected: (connected: boolean) => void,
    setShowParticleEffects: (showParticleEffects: boolean) => void,
    setLogLevel: (logLevel: LogLevel) => void,
    setAutoStart: (autoStart: boolean) => void,
    setFullscreenOnStartup: (fullscreenOnStartup: boolean) => void,
    setDevToolsEnabled: (devToolsEnabled: boolean) => void,
  }

export const createSystemSlice: StateCreator<
    SystemSlice,
    [],
    [],
    SystemSlice
    > = (set) => ({
    screenBrightness: 33,
    adminPin: "",
    adminMode: false,
    appVersion: "unknown",
    analyticsEnabled: false,
    analyticsBackendUrl: "http://localhost:3000/api/gokart",
    analyticsConnected: false,
    gokartLanConnected: false,
    showParticleEffects: true,
    logLevel: "info",
    autoStart: false,
    fullscreenOnStartup: false,
    devToolsEnabled: true,
    setScreenBrightness: (screenBrightness: number) => set({ screenBrightness }),
    setAdminPin: (adminPin: string) => set({ adminPin }),
    setAppVersion: (appVersion: string) => set({ appVersion }),
    setAnalyticsEnabled: (analyticsEnabled: boolean) => set({ analyticsEnabled }),
    setAnalyticsBackendUrl: (analyticsBackendUrl: string) => set({ analyticsBackendUrl }),
    setAnalyticsConnected: (analyticsConnected: boolean) => set({ analyticsConnected }),
    setGokartLanConnected: (gokartLanConnected: boolean) => set({ gokartLanConnected }),
    setShowParticleEffects: (showParticleEffects: boolean) => set({ showParticleEffects }),
    setLogLevel: (logLevel: LogLevel) => set({ logLevel }),
    setAutoStart: (autoStart: boolean) => set({ autoStart }),
    setFullscreenOnStartup: (fullscreenOnStartup: boolean) => set({ fullscreenOnStartup }),
    setDevToolsEnabled: (devToolsEnabled: boolean) => set({ devToolsEnabled }),
})