/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ServiceApplication {
  constructor(serviceId: number)
  init(): void
  start(blocking: boolean): void
  offerMethod(methodId: number, callback: (arg: Array<number>) => number): void
  callMethod(serviceId: number, methodId: number, payload: Array<number>, callback: (arg: Array<number>) => number): void
  offerEvent(eventId: number): void
  subscribe(serviceId: number, eventId: number, callback: (arg: Array<number>) => number): void
}
export type ServiceApplicationJs = ServiceApplication

export interface IpAddressJs {
  a: number
  b: number
  c: number
  d: number
}

export interface MethodCallResult {
  success: boolean
  data?: Buffer
  errorMessage?: string
}

export interface ServiceApplicationConfigJs {
  port: number
  useServiceDiscovery: boolean
}

export interface StaticServiceJs {
  serviceId: number
  ipAddress: IpAddressJs
}
