; PlatformIO Project Configuration File for ARGB LED Hardware Tester
; Board: AZ-Delivery ESP32-WROOM-32 Dev Kit (30-pin or 38-pin NodeMCU-32S)

[env:esp32dev]
platform = espressif32 @ ^6.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_unflags = -std=gnu++11 -std=gnu++14
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=0
lib_deps =
    makuna/NeoPixelBus@^2.8.4

